name: kura
description: "Kura is a Flutter project designed to store card information
  locally on the device, ensuring that the data is secure and cannot be stolen,
  as the application does not have internet access. The app is optimized for
  efficiency, allowing users to quickly copy card details for transactions."
publish_to: "none"
version: 1.1.0+102

environment:
  sdk: ^3.10.4
  flutter: ^3.44.7

dependencies:
  archive: ^4.0.9
  barcode_scan2: ^4.4.0
  barcode_widget: ^2.0.4
  cryptography_plus: ^3.0.0
  crypto: ^3.0.5
  encrypt: ^5.0.3
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.0
  local_auth: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  screen_brightness: ^2.1.11
  sqflite_sqlcipher: ^3.4.1
  url_launcher: ^6.3.1
  zxing_lib: ^1.1.4
  receive_sharing_intent: ^1.9.0
  image: ^4.8.0
  image_cropper: ^12.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: assets/kura_logo.png
  adaptive_icon_background: "#202020"
  adaptive_icon_foreground: assets/kura_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/network/
